services:
  echo:
    build:
      context: .
      dockerfile: docker/echo-server.Dockerfile
    image: local/kong-plugins-echo:latest
    container_name: kong-plugins-echo

  kong:
    build:
      context: .
      dockerfile: docker/kong.Dockerfile
      args:
        INSTALL_NATIVE_BUILD_DEPS: "${INSTALL_NATIVE_BUILD_DEPS:-false}"
    image: local/kong-plugins-builder:3.4.2
    container_name: kong-3.4.2-local
    environment:
      LD_LIBRARY_PATH: /usr/local/lib/kong-plugins
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_LUA_PACKAGE_CPATH: "/usr/local/lib/kong-plugins/?.so;/usr/local/lib/kong-plugins/lib?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/?/init.so;;"
      KONG_LOG_LEVEL: info
      KONG_NATIVE_LIB_DIR: /usr/local/lib/kong-plugins
      KONG_NATIVE_LIBS_SOURCE_DIR: /rocks/native
      KONG_NGINX_MAIN_ENV: LD_LIBRARY_PATH
      KONG_NGINX_WORKER_PROCESSES: "1"
      KONG_PLUGINS: bundled,request-profiler,json-field-guard,canary-header-router
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_REQUIRE_NATIVE_LIBS: "false"
      KONG_REQUIRE_ROCKS: "true"
      KONG_ROCKS_DIR: /rocks
      KONG_STATUS_LISTEN: 0.0.0.0:8100
    depends_on:
      - echo
    ports:
      - "${KONG_PROXY_PORT:-8000}:8000"
      - "${KONG_PROXY_SSL_PORT:-8443}:8443"
      - "${KONG_ADMIN_PORT:-8001}:8001"
      - "${KONG_STATUS_PORT:-8100}:8100"
    volumes:
      - ./build/out:/rocks:ro
      - ./kong/kong.yml:/kong/declarative/kong.yml:ro
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 10
